services:
  user-service:
    build:
      context: ./services/user-service
    container_name: shop-user-service
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file: 
      - ./services/user-service/.env
    depends_on: 
      - user-db
    networks:
      - user-network

  user-db:
    image: postgres:16
    container_name: shop-user-db
    environment:
      POSTGRES_DB: ${USER_DB_NAME}
      POSTGRES_USER: ${USER_DB_USER}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
    volumes:
      - user_postgres_data:/var/lib/postgresql/data
    networks:
      - user-network

  catalog-service:
    build:
      context: ./services/catalog-service
    container_name: shop-catalog-service
    command: python manage.py runserver 0.0.0.0:8001
    ports:
      - "8001:8001"
    env_file:
      - ./services/catalog-service/.env
    depends_on:
      - catalog-db
    networks:
      - catalog-network

  catalog-db:
    image: postgres:16
    container_name: shop-catalog-db
    environment:
      POSTGRES_DB: ${CATALOG_DB_NAME}
      POSTGRES_USER: ${CATALOG_DB_USER}
      POSTGRES_PASSWORD: ${CATALOG_DB_PASSWORD}
    volumes:
      - catalog_postgres_data:/var/lib/postgresql/data
    networks:
      - catalog-network

networks:
  user-network:
  catalog-network:

volumes:
  user_postgres_data:
  catalog_postgres_data: