services:
  api-gateway:
    image: nginx:alpine
    container_name: shop-api-gateway
    ports:
      - "8080:80"
    volumes:
      - ./infrastructure/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - user-service
      - catalog-service

  user-service:
    build:
      context: ./services/user-service
    container_name: shop-user-service
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file: 
      - ./services/user-service/.env
    depends_on: 
      - user-db

  user-db:
    image: postgres:16
    container_name: shop-user-db
    environment:
      POSTGRES_DB: ${USER_DB_NAME}
      POSTGRES_USER: ${USER_DB_USER}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
    volumes:
      - user_postgres_data:/var/lib/postgresql/data

  catalog-service:
    build:
      context: ./services/catalog-service
    container_name: shop-catalog-service
    command: python manage.py runserver 0.0.0.0:8001
    ports:
      - "8001:8001"
    env_file:
      - ./services/catalog-service/.env
    depends_on:
      - catalog-db

  catalog-db:
    image: postgres:16
    container_name: shop-catalog-db
    environment:
      POSTGRES_DB: ${CATALOG_DB_NAME}
      POSTGRES_USER: ${CATALOG_DB_USER}
      POSTGRES_PASSWORD: ${CATALOG_DB_PASSWORD}
    volumes:
      - catalog_postgres_data:/var/lib/postgresql/data

volumes:
  user_postgres_data:
  catalog_postgres_data: